version: '3'

services:
  app:
    build:
      context: .
    command: ["python3", "Main.py"]
    env_file: .env
    environment:
      - WORDLEBOT_REDIS__HOST=${WORDLEBOT_REDIS__HOST:-redis}
      - WORDLEBOT_REDIS__PORT=${WORDLEBOT_REDIS__PORT:-6379}
    volumes:
      - ./:/srv
    depends_on:
      - redis

  redis:
    image: "redis:6.2-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
  redis-conf: